// export const handymanProfessions = [
//   "Carpenter",
//   "Plumber",
//   "Electrician",
//   "Mechanic",
//   "Painter",
//   "Mason",
//   "Roofer",
//   // "HVAC Technician",
//   "Welder",
//   "Locksmith",
//   // "Landscaper",
//   "Gardener",
//   "General Contractor",
//   "Tile Setter",
//   "Drywall Installer",
//   "Cabinet Maker",
//   // "Glazier",
//   // "Fence Installer",
//   "Upholsterer",
//   "Floor Installer",
//   "Pest Control Specialist",
//   // "Chimney Sweep",
//   "Appliance Repair Technician",
//   "Garage Door Installer",
//   "Gutter Cleaner",
//   "Pressure Washer Technician",
//   "Deck Builder",
//   "Window Installer",
//   // "Insulation Installer",
//   "Siding Installer",
//   "Blacksmith",
//   "Pool Maintenance Specialist",
//   "Boat Mechanic",
//   "Solar Panel Installer",
//   "Scaffold Erector",
// ];

export const handymanProfessions = [
  { profession: "Carpenter", skills: ["Woodworking", "Blueprint Reading"] },
  { profession: "Plumber", skills: ["Pipe Installation", "Leak Repair"] },
  { profession: "Electrician", skills: ["Wiring", "Circuit Troubleshooting"] },
  { profession: "Mechanic", skills: ["Engine Repair", "Diagnostic Testing"] },
  { profession: "Painter", skills: ["Surface Preparation", "Color Matching"] },
  { profession: "Mason", skills: ["Bricklaying", "Concrete Mixing"] },
  { profession: "Roofer", skills: ["Shingle Installation", "Leak Prevention"] },
  {
    profession: "HVAC Technician",
    skills: ["System Installation", "Refrigerant Handling"],
  },
  {
    profession: "Welder",
    skills: ["Metal Joining", "Blueprint Interpretation"],
  },
  { profession: "Locksmith", skills: ["Lock Picking", "Key Duplication"] },
  { profession: "Landscaper", skills: ["Garden Design", "Lawn Maintenance"] },
  { profession: "Gardener", skills: ["Plant Care", "Pruning"] },
  {
    profession: "General Contractor",
    skills: ["Project Management", "Budgeting"],
  },
  { profession: "Tile Setter", skills: ["Tile Cutting", "Grouting"] },
  {
    profession: "Drywall Installer",
    skills: ["Drywall Cutting", "Joint Taping"],
  },
  {
    profession: "Cabinet Maker",
    skills: ["Furniture Assembly", "Precision Cutting"],
  },
  { profession: "Glazier", skills: ["Glass Installation", "Sealing"] },
  {
    profession: "Fence Installer",
    skills: ["Post Setting", "Material Cutting"],
  },
  { profession: "Upholsterer", skills: ["Fabric Handling", "Cushion Repair"] },
  {
    profession: "Floor Installer",
    skills: ["Floor Measuring", "Material Installation"],
  },
  {
    profession: "Pest Control Specialist",
    skills: ["Pest Identification", "Chemical Handling"],
  },
  {
    profession: "Chimney Sweep",
    skills: ["Soot Removal", "Chimney Inspection"],
  },
  {
    profession: "Appliance Repair Technician",
    skills: ["Appliance Diagnostics", "Component Replacement"],
  },
  {
    profession: "Garage Door Installer",
    skills: ["Track Alignment", "Motor Installation"],
  },
  { profession: "Gutter Cleaner", skills: ["Debris Removal", "Gutter Repair"] },
  {
    profession: "Pressure Washer Technician",
    skills: ["High-Pressure Cleaning", "Surface Restoration"],
  },
  {
    profession: "Deck Builder",
    skills: ["Wood Cutting", "Structural Assembly"],
  },
  {
    profession: "Window Installer",
    skills: ["Glass Fitting", "Frame Installation"],
  },
  {
    profession: "Insulation Installer",
    skills: ["Material Measurement", "Thermal Barrier Installation"],
  },
  {
    profession: "Siding Installer",
    skills: ["Panel Cutting", "Weatherproofing"],
  },
  { profession: "Blacksmith", skills: ["Metal Forging", "Heat Treatment"] },
  {
    profession: "Pool Maintenance Specialist",
    skills: ["Water Testing", "Filter Cleaning"],
  },
  {
    profession: "Boat Mechanic",
    skills: ["Marine Engine Repair", "Electrical Troubleshooting"],
  },
  {
    profession: "Solar Panel Installer",
    skills: ["Panel Mounting", "Electrical Integration"],
  },
  {
    profession: "Scaffold Erector",
    skills: ["Structure Assembly", "Height Safety"],
  },
  { profession: "Handyman", skills: ["General Repairs", "Problem Solving"] },
];
